apiVersion: apps/v1
kind: Deployment
metadata:
  name: natujenge-frontend
spec:
  selector:
    matchLabels:
      app: natujenge-frontend
  template:
    metadata:
      labels:
        app: natujenge-frontend
    spec:
      containers:
      - name: natujenge-frontend
        image: 40781998/natujenge-frontend
        resources:
          limits:
            memory: "128Mi"
            cpu: "250m"
        ports:
        - containerPort: 80

