# Generated by Django 4.1.2 on 2022-10-10 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('phone_number', models.CharField(max_length=255)),
                ('specialisation', models.CharField(choices=[('backend', 'Backend'), ('frontend', 'Frontend'), ('fullstack', 'Fullstack')], max_length=255)),
            ],
        ),
    ]
