# Generated by Django 4.1.2 on 2022-10-16 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0002_team'),
    ]

    operations = [
        migrations.AddField(
            model_name='bill',
            name='month',
            field=models.CharField(blank=True, choices=[('January', 'January'), ('February', 'February'), ('March', 'March'), ('April', 'April'), ('May', 'May'), ('June', 'June'), ('July', 'July'), ('August', 'August'), ('September', 'September'), ('October', 'October'), ('November', 'November'), ('December', 'December')], max_length=200, null=True),
        ),
    ]
